### ISSUE TITLE
How do I configure the app?

### ISSUE THREAD

**Issue by svallory** [darrencauthon/MvcTurbine.MembershipProvider#4]
How do I configure my mvc app to use this membership provider? I'm already using MvcTurbine and have created a class which extends PrincipalProvider. A running example would be nice.

Thanks!

**Comment by darrencauthon** [comment]
I apologize for not getting to this earlier.  I've been developing on Macs without a MSDN (or even Windows) license for almost two years, and I have not been able to set this up.
